name: SM CLI Build
on: [push]
jobs:
  SM_CLI_build:
    runs-on:
      - codebuild-sm_cli_repo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python3 -m pip install setuptools wheel build   

      - name: Build package
        run: |
          python3 -m build
    
      - name: Upload package
        run: |
          aws s3 cp dist/sm_cli-0.1.0-py3-none-any.whl s3://marc-tests-us-east-1-9514-7953-3181/packages/
          aws s3 sync temporary-credentials/get-credentials/get-credentials.py s3://marc-tests-us-east-1-9514-7953-3181/packages/
